apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureNamedServiceAccount
metadata:
  name: azure-named-service-account
spec:
  match:
    excludedNamespaces: {{ .Values.excludedNamespaces }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
