apiVersion: v1
kind: Pod
metadata:
  name: nginx-service-account
  labels:
    app: nginx-service-account
spec:
  serviceAccountName: test-account
  automountServiceAccountToken: false
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
